# -*- coding: utf-8 -*-
"""Data Science Project 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QwVdeE244azja4xzvPIs7wPEeb3lI6ew
"""

#Melakukan EDA dan Cleansing sederhana
import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Digital Skola/Project 1/Mobile_phone_price.csv")
df.head()

df.shape

df.info() #informasi umum

df.describe() #kenapa price yang juga numerik tipenya objek ?

df['RAM '].unique()

df.columns

df.nunique()

df['Price ($)'].unique()

df['Screen Size (inches)'].unique()

df[(df['Screen Size (inches)'] == '6.8 + 3.9') | (df['Screen Size (inches)'] == '7.6 (unfolded)')]

df['Price ($)'] = df['Price ($)'].str.replace('$','')
df['Price ($)'] = df['Price ($)'].str.replace(',','')
df['Price ($)'] = df['Price ($)'].astype(int)

df.describe()

df['Price ($)'].unique()

import re

df['RAM '] = df['RAM '].str.replace(r'\D+', '', regex=True).astype('int')

df['RAM '].unique()

df.describe()

df.sort_values(by= 'Battery Capacity (mAh)', ascending = False)

df["Battery Dollar"] = df['Battery Capacity (mAh)']/df['Price ($)']

df

#berapa harga paling murah dari semua merk
df.groupby('Brand').agg({'Price ($)': ['min']})

df.groupby('Brand').agg(Rata2_Harga = ('Price ($)', 'mean')).sort_values(by = 'Rata2_Harga')

df.groupby('Brand').agg(Rata2_Harga = ('Price ($)', 'mean'), avg_batteray_cap = ('Battery Capacity (mAh)', 'mean'))

pd.crosstab(df['Brand'], df['RAM '])

df.pivot_table(index = "Brand", values = ['Price ($)', 'Battery Capacity (mAh)'], aggfunc = ['mean', 'max'])

df.pivot_table(index = "Brand", values = ['Price ($)'], columns = "RAM ", aggfunc = ['mean'])

"""**Melt**
> mengubah tabel memanjang ke samping menjadi memanjang ke bawah


"""

df

df_melt = df.melt(id_vars = ['Brand', 'Model', 'Storage ', 'RAM ', 'Screen Size (inches)', 'Camera (MP)'], \
        var_name='kolom_berikutnya', value_name= 'value')

df_melt

df_melt['kolom_berikutnya'].unique()

df.stack().head(40)

df = df.rename(columns = {'Storage ':'Storage', 'RAM ':'RAM'})

df.columns

"""Kategorisasi Value di Kolom"""

#kategorisasi harga hp pakai qcut untuk numerik
bin_label =  ['Bronze', 'Silver', 'Gold', 'Platinum']
results, bin_edges = pd.qcut(df['Price ($)'], q = 4, labels = bin_label, retbins=True)

results.value_counts()

#kategorisasi harga hp pakai qcut
bin_label =  ['Bronze', 'Silver', 'Gold', 'Platinum']
results, bin_edges = pd.qcut(df['Battery Dollar'], q = 4, labels = bin_label, retbins=True)

results.value_counts()

df['Price Category'] = results

df

df['rank_price'] = df['Price ($)'].rank(ascending = True, method = 'first')
df